@startuml
'https://plantuml.com/activity-diagram-beta
skinparam maxMessageSize 50
start

:Put basilisks on the map;

partition Running {
    repeat
        if (Has a student stepped on his position?) then (yes)
            :Kill the student;
        else (no)
        endif

        :Wait for basilisk's turn;
        partition Turn {
            :Move to another location;
            if (Map checks if anything is on this position?) then (yes)
                if (Is this a a student?) then (yes)
                    :Kill the student;
                else (no)
                endif
            else (no)
            endif
        }
    repeat while (Number of iterations reached?) is (no)
->yes;
}

stop

@enduml
