@startuml
'https://plantuml.com/use-case-diagram

left to right direction
actor Actor
rectangle Simulation {
  usecase "Run Simulation" as UC1
  usecase "Set space size" as UC2
  usecase "Set number of students" as UC3
  usecase "Set number of iterations" as UC4
  usecase "Get results" as UC5
}
Actor --> UC1
Actor --> UC2
Actor --> UC3
Actor --> UC4
Actor --> UC5
@enduml