@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

package hogwartSim.interactions{
    interface IInteractionAgent{

    }
    class InteractionAgent{
        +action(ICreature, IMap: void
        +handleCreatureMeeting(ICreature, IMap);
        +handleItemMeeting(ICreature, IMap);
        +studentAction(Student, List<ICreature>): void
        +getBasiliskFromCreatureList(List<ICreature>): List<Basilisk>
        +teacherAction(Teacher, List<ICreature>): void
        +basiliskAction(Basilisk, List<ICreature>): void

    }
IInteractionAgent <|-- InteractionAgent
}

@enduml