@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

package hogwartSim{
    class Simulation{
        -map: IMap
        -rnd: Rnd
        -generalList: List<IGeneral>
        -numIter: int
        -pointList: List<IPointGetter>

        +Simulation(IMapCreator, IGeneralCreator, IDumbledoreCreator, long, int)
        +runSimulation(): void
        +main(String[]): void
    }
}

package hogwartSim.general{
    interface IGeneral
}
Simulation *- IGeneral: generalList

package hogwartSim.map{
    interface IMap
}
Simulation *- "map" IMap

package hogwartSim.dumbledore{
    interface IDumbledore
}
Simulation *- IDumbledore: pointList


@enduml