@startuml
'https://plantuml.com/sequence-diagram

'autonumber

General -> General: Generate random\nlocation to move
General -> Student: Move
Student -> MaraudersMap: Change position
MaraudersMap -> General: Done
General-> MaraudersMap: Check position
MaraudersMap -> General: Who is on the position
@enduml